import scipy as sp
from scipy import constants

print(f'SciPy version: {sp.__version__}')

print(' METRIC PREFIXES:')
print(f'Yotta: {constants.yotta}')
print(f'Zetta: {constants.zetta}')
print(f'  Exa: {constants.exa}')
print(f' Peta: {constants.peta}')
print(f' Tera: {constants.tera}')
print(f' Giga: {constants.giga}')
print(f' Mega: {constants.mega}')
print(f' Kilo: {constants.kilo}')
print(f'Hecto: {constants.hecto}')
print(f' Deka: {constants.deka}')
print(f' Deci: {constants.deci}')
print(f'Centi: {constants.centi}')
print(f'Milli: {constants.milli}')
print(f'Micro: {constants.micro}')
print(f' Nano: {constants.nano}')
print(f' Pico: {constants.pico}')
print(f'Femto: {constants.femto}')
print(f' Atto: {constants.atto}')
print(f'Zepto: {constants.zepto}')

print('\n BINARY PREFIXES:')
print(f'Kibi: {constants.kibi}')
print(f'Mebi: {constants.mebi}')
print(f'Gibi: {constants.gibi}')
print(f'Tebi: {constants.tebi}')
print(f'Pebi: {constants.pebi}')
print(f'Exbi: {constants.exbi}')
print(f'Zebi: {constants.zebi}')
print(f'Yobi: {constants.yobi}')

print('\n MASS:')
print(f'Gram: {constants.gram}')
print(f'Metric ton: {constants.metric_ton}')
print(f'Grain: {constants.grain}')
print(f'Pound (lb): {constants.lb}')
print(f'Pound: {constants.pound}')
print(f'Ounce (oz): {constants.oz}')
print(f'Ounce: {constants.ounce}')
print(f'Stone: {constants.stone}')
print(f'Long ton: {constants.long_ton}')
print(f'Short ton: {constants.short_ton}')
print(f'Troy ounce: {constants.troy_ounce}')
print(f'Troy pound: {constants.troy_pound}')
print(f'Carat: {constants.carat}')
print(f'Atomic mass: {constants.atomic_mass}')
print(f'Mean unified atomic mass (m_u): {constants.m_u}')
print(f'Unified atomic mass unit (u): {constants.u}')

print('\n ANGLE:')
print(f'Degree: {constants.degree}')
print(f'Arcminute (arcmin): {constants.arcmin}')
print(f'Arcminute: {constants.arcminute}')
print(f'Arcsecond (arcsec): {constants.arcsec}')
print(f'Arcsecond: {constants.arcsecond}')

print('\n TIME:')
print(f'Minute: {constants.minute}')
print(f'  Hour: {constants.hour}')
print(f'   Day: {constants.day}')
print(f'  Week: {constants.week}')
print(f'  Year: {constants.year}')
print(f'Julian year: {constants.Julian_year}')

print('\n LENGTH:')
print(f'Inch: {constants.inch}')
print(f'Foot: {constants.foot}')
print(f'Yard: {constants.yard}')
print(f'Mile: {constants.mile}')
print(f'Mil: {constants.mil}')
print(f'Point (pt): {constants.pt}')
print(f'Point: {constants.point}')
print(f'Survey foot: {constants.survey_foot}')
print(f'Survey mile: {constants.survey_mile}')
print(f'Nautical mile: {constants.nautical_mile}')
print(f'Fermi: {constants.fermi}')
print(f'Angstrom: {constants.angstrom}')
print(f'Micron: {constants.micron}')
print(f'Astronomical unit (au): {constants.au}')
print(f'Astronomical unit: {constants.astronomical_unit}')
print(f'Light year: {constants.light_year}')
print(f'Parsec: {constants.parsec}')

print('\n PRESSURE:')
print(f'Atmosphere (atm): {constants.atm}')
print(f'Atmosphere: {constants.atmosphere}')
print(f'Bar: {constants.bar}')
print(f'Torr: {constants.torr}')
print(f'Millimeter of mercury (mmHg): {constants.mmHg}')
print(f'Pound per square inch (psi): {constants.psi}')

print('\n AREA:')
print(f'Hectare: {constants.hectare}')
print(f'Acre: {constants.acre}')

print('\n VOLUME:')
print(f'Liter: {constants.liter}')
print(f'Litre: {constants.litre}')
print(f'Gallon: {constants.gallon}')
print(f'Gallon (US): {constants.gallon_US}')
print(f'Gallon (Imperial): {constants.gallon_imp}')
print(f'Fluid ounce: {constants.fluid_ounce}')
print(f'Fluid ounce (US): {constants.fluid_ounce_US}')
print(f'Fluid ounce (Imperial): {constants.fluid_ounce_imp}')
print(f'Barrel: {constants.barrel}')
print(f'Barrel (bbl): {constants.bbl}')

print('\n SPEED:')
print(f'Kilometer per hour (km/h): {constants.kmh}')
print(f'Mile per hour (mph): {constants.mph}')
print(f'Mach: {constants.mach}')
print(f'Speed of sound: {constants.speed_of_sound}')
print(f'Knot: {constants.knot}')

print('\n TEMPERATURE:')
print(f'Zero Celsius: {constants.zero_Celsius}')
print(f'Degree Fahrenheit: {constants.degree_Fahrenheit}')

print('\n ENERGY:')
print(f'Electron Volt (eV): {constants.eV}')
print(f'Electron Volt: {constants.electron_volt}')
print(f'Calorie: {constants.calorie}')
print(f'Calorie (thermal): {constants.calorie_th}')
print(f'Calorie (International): {constants.calorie_IT}')
print(f'Erg: {constants.erg}')
print(f'British Thermal Unit (Btu): {constants.Btu}')
print(f'British Thermal Unit (Imperial): {constants.Btu_IT}')
print(f'British Thermal Unit (thermal): {constants.Btu_th}')
print(f'Ton of TNT: {constants.ton_TNT}')

print('\n POWER:')
print(f'Horsepower (hp): {constants.hp}')
print(f'Horsepower: {constants.horsepower}')

print('\n FORCE:')
print(f'Dyne (dyn): {constants.dyn}')
print(f'Dyne: {constants.dyne}')
print(f'Pound-force (lbf): {constants.lbf}')
print(f'Pound-force: {constants.pound_force}')
print(f'Kilogram-force (kgf): {constants.kgf}')
print(f'Kilogram-force: {constants.kilogram_force}')

# SOURCE:
# https://www.w3schools.com/python/scipy/scipy_getting_started.php
# https://www.w3schools.com/python/scipy/scipy_constants.php
